### ISSUE TITLE
How to understand the function `cavity_distribution_tied` in file `basemodels.py` ?

### ISSUE THREAD

**Issue by Fangwq** [AaltoML/BayesNewton#8]
Just as the title said, how can I understand `cavity_distribution_tied` in file `basemodels.py`? Is there any reference I should follow up? And I note that this code is similar to equation (64) in the BayesNewton paper. How does it come from?

**Comment by wil-j-wil** [comment]
This is the cavity distribution for Stochastic PEP, where all the sites are assumed equal, and therefore all the cavities are equal too (so you only have to compute and store it once rather than for every data point). This is mentioned in the paper in the last paragraph of Section 8.2 (before 8.2.1).
